# Generated by Django 5.1.2 on 2024-10-15 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco_MEI',
            fields=[
                ('id_endereco_mei', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=45)),
                ('rua', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco_User',
            fields=[
                ('id_endereco_user', models.AutoField(primary_key=True, serialize=False)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=45)),
                ('rua', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('cpf_entregador', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo_entrega', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=45)),
                ('desconto', models.BooleanField(default=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome', models.CharField(max_length=45)),
                ('desconto_produto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cupom_fiscal', models.CharField(max_length=45)),
                ('entrega', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='MEI',
            fields=[
                ('id_mei', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('nome', models.CharField(max_length=45)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('id_endereco_mei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meis', to='api.endereco_mei')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('id_endereco_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.endereco_user')),
            ],
        ),
        migrations.CreateModel(
            name='Fidelidade',
            fields=[
                ('id_fidelidade', models.AutoField(primary_key=True, serialize=False)),
                ('qtd', models.IntegerField()),
                ('descontos', models.FloatField()),
                ('id_mei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidades', to='api.mei')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fidelidades', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Produto_Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_mei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produtos_vendas', to='api.mei')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produtos_vendas', to='api.produto')),
                ('id_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_produtos_vendas', to='api.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encomenda', models.DateTimeField(auto_now_add=True)),
                ('data_entrega', models.DateTimeField()),
                ('qtd', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_mei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api.mei')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api.user')),
                ('id_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='api.venda')),
            ],
        ),
        migrations.CreateModel(
            name='Venda_Realizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_realizadas', to='api.entregador')),
                ('id_endereco_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_realizadas', to='api.endereco_user')),
                ('id_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_realizadas', to='api.venda')),
            ],
        ),
    ]
